export type CategoryKey = 
    | "PRAISE" 
    | "PRAYER" 
    | "THANKSGIVING"
    | "CHRISTIAN_LIVING"
    | "DEVOTIONAL"
    | "WORSHIP"
    | "CONFESS"
    | "TESTIMONY"
    | "MISCELLANEOUS"
    | "All"